version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_1703_2Project
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: WmSalesforceRESTProvider
  version: 12.0.0.0.16
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
services:
- serviceName: project.kvv_1703_2.WmSalesforceRESTProvider.com_webmethods_cloudstreams_salesforce_rest_v60.connections:restAccount
  packages:
  - name: Kvv_1703_2Project
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 12.0.0.0.16
configurationVariables:
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.oauth_v20.authorizationHeaderInTokenRefresh
  : "false"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.oauth.consumerSecret
  : "{AES}8bc8/WHaL3dph5PtuD02009Twi827NgOvyLy8mkfF31b5gfhajCNPAG/2OxW9yx8fPwx12ONSDGw1NRjVAxIemmK1wuN3U1rA1B0VhuZoUw="
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.oauth.consumerId
  : 3MVG9pe2TCoA1Pf6F9PMP1LEDsuYm6pfL6T8OD7YSQUQsx36uZNIjUH3BCzBZ8lgStKaUEITogkQ7hNByxJjv
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.oauth_v20.refreshAccessToken
  : "true"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.oauth_v20.authenticationServerUrl
  : https://login.salesforce.com/services/oauth2/token
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.oauth_v20.scope
  : offline_access api refresh_token
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.retryCount
  : "4"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.poolable
  : "true"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.providerUrl
  : https://d0o000001qr6keac-dev-ed.my.salesforce.com
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.oauth_v20.authorizationServerUrl
  : https://login.salesforce.com/services/oauth2/authorize
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.oauth_v20.accessTokenRefreshURL
  : https://login.salesforce.com/services/oauth2/token
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.oauth_v20.authorizationHeaderPrefix
  : Bearer
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.oauth_v20.refreshToken
  : "{AES}iVEYOEICT1x7P9RL3dwVv0pQv1IODTw0Qm0vrSHPR8I0XZ0/KrBE7WODHo6AzR1637cjFT8vTWSxMJCq+8Fwx23ujlk6B/pLD2FnkHRwbbHw+MNh1fzWP9ra98cky/Z+"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.readTimeout
  : "30000"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.oauth_v20.accessTokenRefreshURLRequest
  : URL Query String
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.connectTimeout
  : "30000"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.timeoutType
  : auto
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cx.grant_type
  : refresh_token
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.oauth.accessToken
  : "{AES}bzO+KX5xKoE0CKrgiYZryEJCc28x2QBODfJSJ6CleRFa+2DzxictbQsvDI2sVqSPyla7tLzWYTVeW/YHTq2TnIndWhV0t/tnSTjg5GXclIH2589LJj3W7DaymwFSO9GDthMYCsMRtvjnQ85gGn25EWmK1wuN3U1rA1B0VhuZoUw="
  ? cloudstreamsconnection.project..kvv_1703_2..WmSalesforceRESTProvider..com_webmethods_cloudstreams_salesforce_rest_v60..connections:restAccount.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
